# Generated by Django 3.2.9 on 2021-11-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20211119_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsale',
            name='item_model',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
